### PR TITLE
Go rewrite

### PR DESCRIPTION
**Pull request by marshyski**
This is a rewrite from Python to Go.  It is backwards compatible with the REST interfaces and configurations minus the rate limiting (buffering was added to depreciate that feature).  All libraries are vendored in this project so it can be checked out and built without pulling from internet sources.  There are a couple of optimizations in this implementation (listed below).  You should get next to no-blocking of uploading RPMs to a repo with this implementation.  Still have to tweak the buffering to do batches in high-stress periods.  Performance benefits should be at least 3-10x improvement and minus the operational hassles of a Python project, see issue #5 

Performance benefits:
1. No need to write / read JSON file on disk, cacheing of contents from the sqlite DB, cache is invalided when new RPM is added and successful read from sqlite is completed.
2. No process is triggered after every request is made that was using subprocess pop.  This is now handled by the buffer to control new RPMs being added.
3.  No need for WSGI server / workers to scale python API.  Go implementation excels at this this even without NGINX to handle other magic.
4.  Even with cache'ing the runtime requires less memory and CPU cycles.

### CODE REVIEW

**Comment by kood1** [comment]
@marshyski - can you write a quick description of the change or link to an issue?  thanks.

**Comment by marshyski** [comment]
@kood1 updated description of PR.

**Comment by kood1** [comment]
Thanks @marshyski.  It looks like CI build is failing.  Can you take a look?

**Comment by kood1** [comment]
@marshyski nvm, it passed

**Pull request merged**
